### ISSUE TITLE
[Enhancement] Add YTDisableHighContrastIcons

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#169]
### Describe this
I am the one who made this one and since I was a bad coder, I didn’t physically make it simple as the Oled Darkmode by BandarHL, so I added .txts of the code I somewhat tried to make

### The Colours + Problem
YouTube Dark Mode + OLED - 909090
YouTube Light Mode - 808080
These were the colors I was trying to configure for uYouPlus, but I pretty much failed on the coding since adding a custom option in settings is hard and configuring, and you might be right on why this was never added.

### Tweak + Inspiration:
Tweak:
https://github.com/arichorn/YTDisableHighContrastIcons/

Inspired By pixdoet (the dude who brought back the old icon colors on desktop)
https://greasyfork.org/en/scripts/431027-youtube-remove-thin-icons

**Comment by qnblackcat** [comment]
I'm not sure I understand your point? what is "high constract icon"?

**Comment by arichorn** [comment]
High Contrast Icons are like Very Bright Icons that’s for colorblind users and in light mode all the icons are black, this was supposed to allow you to disable them and then it will be using hex colors from like it was on the good old youtube versions, also having this option is really good for users who has eye straining issues when looking at the icons
Example:
![7BEE332F-3B7F-4D4A-8CE8-85ABC020F1F7](https://user-images.githubusercontent.com/78001398/169147380-d429f700-6078-480f-9320-fa85fe969a46.jpeg)
This is what it would look like after removing, this image isn’t official but it will help the users out who hates very bright or very dark icons.

**Comment by arichorn** [comment]
Here’s this, these were obviously photoshopped by me but these are the icons with this suggestion 

Dark Mode (Concept)
![2572AD7D-0C5C-42B2-BB8E-53E30D4E0919](https://user-images.githubusercontent.com/78001398/169676616-ffc9b042-f89e-4717-8403-bb96b4cabdb4.jpeg)
Light Mode (Concept)
![38A126E5-35AA-4A03-9587-5AA3533AA53A](https://user-images.githubusercontent.com/78001398/169676619-c96ad062-15bc-4d8f-b1b7-440497ac6fe7.jpeg)

**Comment by arichorn** [comment]
and here’s extra
![BF6A9129-CE89-489D-964B-ACD8D91BEB93](https://user-images.githubusercontent.com/78001398/169677085-e9dc57d6-8f78-4170-b8d3-e61380185910.jpeg)

![6107C134-4484-4BE3-903F-8F09B1AE7732](https://user-images.githubusercontent.com/78001398/169677089-0d683efb-9799-4105-9852-96cf1da02e97.jpeg)
This has to be the best thing I ever suggested, it took me an hour to photoshop every image but I hope these will make uyouplus awesome with customization changes

**Comment by arichorn** [comment]
Oh yeah I forgot to tell you, these are the only images I did for every concept of what it would’ve looked like and it took me 2 hours all together to photoshop a lot of these photos and qnblackcat tell me what you think about these since I’m just sad that YouTube didn’t keep this, since very bright or very dark contrast colors does give problems to a persons eye but only to some people. but the most important thing about this is this giving us a whole new level of customization within the uYouPlus app just like Oled Dark Mode & Oled Keyboard, I’m sorry if this tweak possibly won’t work qnblackcat.

**Comment by qnblackcat** [comment]
Since v17.xx, many UI in the YouTube app are server-side, which can't be modified. You have to use YTDisableHighContrastIcons with **Fake YouTube Version** in YouPiP's setting enabled. Best I can do is this:
```
%group gYTDisableHighContrastIcons
%hook YTCommonColorPalette
- (UIColor *)textPrimary {
    if (self.pageStyle == 1) {
        return [UIColor colorWithWhite:0.565 alpha:1];
    }
        return [UIColor colorWithWhite:0.5 alpha:1];
}
- (UIColor *)textSecondary {
    if (self.pageStyle == 1) {
        return [UIColor colorWithWhite:0.565 alpha:1];
    }
        return [UIColor colorWithWhite:0.5 alpha:1];
}
%end
%end
```

[uYouPlus.xm](https://pastebin.com/2NsD8hM7)
[Settings.xm](https://pastebin.com/FZcpGsUG)
I won't merge YTDisableHighContrastIcons with upstream uYouPlus. You better build the IPA yourself

**Comment by arichorn** [comment]
Oh, it’s fine, I tried making this tweak work, I was trying to let anyone be able to switch from black/white back to gray if they needed. I’m a terrible tweaker qnblackcat.

**Comment by arichorn** [comment]
And the unfortunate thing is I am unable to create any ipa like you said, I sadly don’t own a Mac and unable to use Xcode, but I did add the code onto this in my repo version but for now I’ll see if there’s other solutions for me to create an ipa without a Mac

**Comment by qnblackcat** [comment]
> I’m trying to do it.
> ![77FE0A63-DC43-4D8C-B329-D36E94591816](https://user-images.githubusercontent.com/78001398/172073368-9c17a65a-a255-45c7-8fb3-a135c0efe416.jpeg)
> ![1AA98067-19AC-4AB7-9374-5740C09F7CF9](https://user-images.githubusercontent.com/78001398/172073348-0f3b8f57-41fd-45da-8431-842e9a3f7085.jpeg)

***

I‘ve already added a switch for the tweak. See the `Settings.xm` file above. You don’t have to do it.

> …I’ll see if there’s other solutions for me to create an ipa without a Mac…

You can setup xcode & theos via Github action. This is an example: https://github.com/ISnackable/CercubePlus

**Comment by arichorn** [comment]
I’m terribly sorry about that, I’m on this https://github.com/arichorn/uYouPlusExtra
and I am sorry that I failed on this Tweak and even the ipa itself, creating an ipa with theos or Xcode is pretty tough to do. the Theos errors are on the repo due to my first time building an ipa on a pc or tablet.
![199039D6-5B5A-4E85-941F-329023842FC4](https://user-images.githubusercontent.com/78001398/172088317-ce6d378d-7cfa-4cdd-9c22-c1eada56a998.jpeg)

**Comment by arichorn** [comment]
This was the theos I tried doing, I’m sorry that I’m bad at trying to make all of this work alternatively.
```
name: Build and Release uYouPlus

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of uYou you want to package"
        default: "2.1"
        required: false
        type: string
      decrypted_youtube_url:
        description: "The URL to the decrypted YouTube ipa to package"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-latest

    steps:
      - name: Set Env
        run: echo "workspace=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid xz

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download iOS 15 SDK
        run: |
          curl -LO https://github.com/chrisharper22/sdks/archive/main.zip
          TMP=$(mktemp -d)
          unzip -qq main.zip -d $TMP
          mv $TMP/sdks-main/*.sdk $THEOS/sdks
          rm -r main.zip $TMP
        env:
          THEOS: ${{ env.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v3
        with:
          repository: kabiroberai/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ env.workspace }}/theos

      - name: Build Package
        id: build_package
        run: |
          cd ${{ env.workspace }}/main
          make package FINALPACKAGE=1
          echo "::set-output name=package::$(ls -t packages | head -n1)"
        env:
          THEOS: ${{ env.workspace }}/theos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ github.event.inputs.uyou_version }}
        with:
          tag_name: v${{ github.run_number }}-${{ env.UYOU_VERSION }}
          release_name: Release v${{ github.run_number }}-${{ env.UYOU_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ github.event.inputs.uyou_version }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          asset_name: uYouPlus${{ github.run_number }}-${{ env.UYOU_VERSION }}.ipa
          asset_content_type: application/vnd.debian.binary-package
```
